DELIMITER;
SELECT 'Creando Usuarios y Permisos' AS 'Estado';
DROP USER if EXISTS 'test'@'localhost';
CREATE USER 'test'@'loclahost' IDENTIFIED BY 'T12-test';
GRANT SELECT ON 5to_Espuchifai.* TO 'test'@'localhost';
GRANT UPDATE ON 5to_Espuchifai.* TO 'test'@'localhost';
GRANT DELETE ON 5to_Espuchifai.* TO 'test'@'localhost';
GRANT EXECUTE ON PROCEDURE altaBandas TO 'test'@'localhost';
GRANT EXECUTE ON PROCEDURE altaAlbumes TO 'test'@'localhost';
GRANT EXECUTE ON PROCEDURE altaCanciones TO 'test'@'localhost';
